# Generated by Django 4.2.7 on 2023-12-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_name_useraccount_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='cart',
        ),
    ]
