# Generated by Django 4.2.7 on 2023-11-15 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug категории')),
            ],
            options={
                'verbose_name': 'Список категорий',
                'verbose_name_plural': 'Список категорий',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название подкатегории')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'Список подкатегорий',
                'verbose_name_plural': 'Список подкатегорий',
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название товара')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('volume_or_weight', models.CharField(max_length=255)),
                ('composition', models.TextField()),
                ('storage_conditions', models.TextField()),
                ('storage_period', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.group')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Список товаров',
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.subcategory'),
        ),
    ]
