# Generated by Django 4.2.7 on 2023-12-06 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug категории')),
                ('image', models.ImageField(blank=True, default='img/category/default.jpg', upload_to='img/category', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Список категорий',
                'verbose_name_plural': 'Список категорий',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название подкатегории')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug подкатегории')),
                ('image', models.ImageField(blank=True, default='img/subcategory/default.jpg', upload_to='img/subcategory', verbose_name='Изображение подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'Список подкатегорий',
                'verbose_name_plural': 'Список подкатегорий',
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название товара')),
                ('feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='Особенность товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('small_image', models.ImageField(blank=True, default='img/products/small/default.jpg', upload_to='img/products/small', verbose_name='Маленькое изображение товара')),
                ('large_image', models.ImageField(blank=True, default='img/products/large/default.jpg', upload_to='img/products/large', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Процент скидки')),
                ('calories', models.TextField(blank=True, null=True, verbose_name='Ккал')),
                ('proteins', models.TextField(blank=True, null=True, verbose_name='Белки')),
                ('fats', models.TextField(blank=True, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.TextField(blank=True, null=True, verbose_name='Углеводы')),
                ('volume_or_weight', models.TextField(blank=True, max_length=255, null=True, verbose_name='Вес/объём')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Состав')),
                ('storage_period', models.TextField(blank=True, null=True, verbose_name='Срок хранения')),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='Условия хранения')),
                ('manufacturer', models.TextField(blank=True, null=True, verbose_name='Производитель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.group', verbose_name='Группа товара')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Список товаров',
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.subcategory'),
        ),
    ]
