# Generated by Django 4.2.7 on 2023-11-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/category/default.jpg', upload_to='img/category', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='large_image',
            field=models.ImageField(blank=True, default='img/products/large/default.jpg', upload_to='img/products/large', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.ImageField(blank=True, default='img/products/small/default.jpg', upload_to='img/products/small', verbose_name='Маленькое изображение товара'),
        ),
    ]
