# Generated by Django 4.2.7 on 2023-11-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_product_discount_product_large_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_info',
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.TextField(blank=True, null=True, verbose_name='Количество ккал'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.TextField(blank=True, null=True, verbose_name='Количество углеводов'),
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.TextField(blank=True, null=True, verbose_name='Количество жиров'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Особенность товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.TextField(blank=True, null=True, verbose_name='Количество белка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.group', verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(blank=True, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия хранения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_period',
            field=models.TextField(blank=True, null=True, verbose_name='Срок хранения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_or_weight',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вес/объём'),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
