# Generated by Django 4.2.7 on 2023-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_nutritional_info_product_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='img/subcategory/default.jpg', upload_to='img/subcategory', verbose_name='Изображение подкатегории'),
        ),
    ]
