# Generated by Django 4.2.7 on 2023-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
