# Generated by Django 4.2.7 on 2023-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.TextField(blank=True, null=True, verbose_name='Ккал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.TextField(blank=True, null=True, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.TextField(blank=True, null=True, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.TextField(blank=True, null=True, verbose_name='Белки'),
        ),
    ]
